amazon_key: ""

email:
  host: ""
  user: ""
  passwd: ""

db:
  mongo:
    user: ""
    passwd: ""

  psql:
    name: ""
    user: ""
    passwd: ""
    HOST: ""
    PORT: ""

path:
  static_root: ""
  media_root: ""

paymill:
  private: ""
  public: ""

secret_key: ""

tmp:
  kooblit_tmp_root: ""
