amazon_key: ""

email:
  host: ""
  user: ""
  passwd: ""

db:
  mongo:
    user: ""
    passwd: ""

  psql:
    name: ""
    user: ""
    passwd: ""

path:
  static_root: ""
  media_root: ""

paymill:
  priv: ""
  pub: ""

secret_key: ""
